name: Build test with NDK on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Set up NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
        unzip android-ndk-r21d-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r21d
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME" >> $GITHUB_PATH
      if: matrix.os == 'ubuntu-latest'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_ENV"

    - name: Configure CMake for Unix-like OS
      if: matrix.os != 'windows-latest'
      run: >
        cmake -B ${{ github.workspace }}/test/build
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
        -DANDROID_PLATFORM=android-21
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}/test  

    - name: Configure CMake for Windows
      if: matrix.os == 'windows-latest'
      run: >
        cmake -B ${{ github.workspace }}/test/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}/test  

    - name: Build
      run: cmake --build ${{ github.workspace }}/test/build --config ${{ matrix.build_type }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-${{ matrix.os }}-${{ matrix.c_compiler }}
        path: ${{ github.workspace }}/test/build/**
